

services:
  postgres:
    image: postgres:15
    container_name: expense_tracker_postgres
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: ./expensetracker.dockerfile
    container_name: expense_tracker_web
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    env_file:
      - .env

volumes:
  postgres-data:
