

services:
  postgres:  # Service name should be properly indented under 'services'
    image: postgres:15
    container_name: expense_tracker_postgres  # Use underscores, not hyphens, for container name key
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ExpenseTrackerdb
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Correct indentation and format for volumes
    ports:
      - "5432:5432"  # Correct indentation and format for ports

  web:
    build:
      context: .
      dockerfile: ./expensetracker.dockerfile
    container_name: expense_tracker_web
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://ExpenseTrackerdb_owner:teXZD6bP1kHh@ep-billowing-breeze-a83cg8i2.eastus2.azure.neon.tech/ExpenseTrackerdb?sslmode=require
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    env_file:
      - .env

volumes:
  postgres-data:
